#!/bin/bash
current_dir=$(pwd)

ln -sv ${current_dir}/.commonrc ~
ln -sv ${current_dir}/.bash_profile ~
ln -sv ${current_dir}/.zshrc ~
ln -sv ${current_dir}/.gitconfig ~
ln -sv ${current_dir}/.zsh ~
ln -sv ${current_dir}/.z.sh ~
